cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'


urlpatterns = [
    path('view_cart/', views.view_cart, name='view_cart'),
    path('remove/<item_id>', views.remove_item, name='remove_item'),
    path('add_item/<item_id>', views.add_item, name='add_item'),
    path('check_out/', views.check_out, name='check_out'),
    path('payments/', views.payments, name='payments'),
]

core/urls.py
from django.urls import path
from core import views

app_name = 'core'


urlpatterns = [
    path('index/', views.index, name='index')
]

items/urls.py
from django.urls import path
from items import views


app_name = 'items'

urlpatterns = [
    path('search_item/', views.search_item , name='search_item'),
    path('view_item_details/<item_id>', views.view_item_details, name='view_item_details'),
]

shopping_project/urls.py
from django.contrib import admin
from django.urls import path, include
import users
import core
from items.views import search_item
import cart


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('users.urls'), name='user_login'),
    path('', include('core.urls')),
    # path('search_item/', search_item, name='search_item'),
    # path('users/', include('users.urls')),
    path('items/', include('items.urls')),
    path('cart/', include('cart.urls')),
    path('users/user_login/', users.views.user_login, name='login')
]

cart/models.py
from django.db import models
from items.models import Item
# Create your models here.


class Cart(models.Model):
    cart_id = models.IntegerField(primary_key=True)
    cart_item = models.ManyToManyField(Item)

    def __str__(self):
        return f"{self.cart_id}, {self.cart_item}"

cart/views.py
from django.shortcuts import render,redirect
from users.models import UserProfile
from items.models import Item
from django.contrib.auth.admin import User
from django.contrib.auth.decorators import login_required

# Create your views here.


@login_required(login_url="/users/user_login/")
def view_cart(request):
    current_user_name = request.user.username
    user = User.objects.filter(username=current_user_name).first()
    user_loggedin = UserProfile.objects.filter(user = user).first()
    items = user_loggedin.cart.cart_item.all()
    total = 0
    for item in items:
        total += (item.item_price*(1 - (item.item_discount)/100))

    return render(request, 'cart/cart.html', {'items':items, 'cart_total':total})


@login_required(login_url="/users/user_login/")
def remove_item(request, item_id):
    current_user_name = request.user.username
    user = User.objects.filter(username=current_user_name).first()
    user_loggedin = UserProfile.objects.filter(user=user).first()
    item = user_loggedin.cart.cart_item.get(pk=item_id)
    user_loggedin.cart.cart_item.remove(item)
    items = user_loggedin.cart.cart_item.all()
    return render(request, 'cart/cart.html', {'items':items})


@login_required(login_url="/users/user_login/")
def add_item(request, item_id):
    item_id = int(item_id)
    current_user_name = request.user.username
    user = User.objects.filter(username=current_user_name).first()
    user_loggedin = UserProfile.objects.filter(user=user).first()
    item = Item.objects.get(pk=item_id)
    user_loggedin.cart.cart_item.add(item)
    items = user_loggedin.cart.cart_item.all()
    return redirect('cart:view_cart')


@login_required(login_url="/users/user_login/")
def check_out(request):
    current_user_name = request.user.username
    user = User.objects.filter(username=current_user_name).first()
    user_loggedin = UserProfile.objects.filter(user=user).first()
    items = user_loggedin.cart.cart_item.all()
    print(items)
    print(type(items))
    for item in items:
        user_loggedin.cart.cart_item.remove(item)
    return render(request, 'cart/payment.html')


@login_required(login_url="/users/user_login/")
def payments(request):
    return render(request, 'cart/order_success.html')

templates/cart/cart.html
{% extends 'core/base.html'%}
{% load custom_tags %}
{% load static %}
{% block content %}

{% for item in items %}

<div class="card shadow p-3 mb-5 bg-white rounded">
    <div class="card-body">
      <a href="{% url 'items:view_item_details' item.id %}"><h5 class="card-title">{{item.item_name}}</h5></a>
      <p class="card-text"><small class="text-muted">{{item.item_discount}} % off</small></p>

    </div>
    </div>

    <form action="{% url 'cart:remove_item' item.id %}">
        <input type="submit" class="btn btn-primary" value="Remove"></input><h1></h1>
    </form>
{% endfor %}
{% if items %}

<h1>Cart total - {{cart_total}} INR</h1>
<form action="{% url 'cart:check_out' %}">
<button class="btn btn-primary">Check out</button>
</form>
{%else%}
<h1>Your cart is empty!</h1>
{% endif %}
{% endblock %}

templates/cart/order_success.html
{% extends 'core/base.html' %}
{% block content %}

<h1>Order Placed</h1>
<form action="{% url 'core:index'%}">
<button class="btn btn-primary">Keep Shopping</button>
</form>
{% endblock %}

templates/cart/payment.html
{% extends 'core/base.html' %}
{% block content %}

<h1>Placing order?</h1>
<form action="{% url 'cart:payments' %}">
<button class="btn btn-primary">Place order</button>
</form>
{% endblock %}