cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'


urlpatterns = [
    path('view_cart/', views.view_cart, name='view_cart'),
    path('remove/<item_id>', views.remove_item, name='remove_item'),
    path('add_item/<item_id>', views.add_item, name='add_item'),
    path('check_out/', views.check_out, name='check_out'),
    path('payments/', views.payments, name='payments'),
]

core/urls.py
from django.urls import path
from core import views

app_name = 'core'


urlpatterns = [
    path('index/', views.index, name='index')
]

items/urls.py
from django.urls import path
from items import views


app_name = 'items'

urlpatterns = [
    path('search_item/', views.search_item , name='search_item'),
    path('view_item_details/<item_id>', views.view_item_details, name='view_item_details'),
]

shopping_project/urls.py
from django.contrib import admin
from django.urls import path, include
import users
import core
from items.views import search_item
import cart


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('users.urls'), name='user_login'),
    path('', include('core.urls')),
    # path('search_item/', search_item, name='search_item'),
    # path('users/', include('users.urls')),
    path('items/', include('items.urls')),
    path('cart/', include('cart.urls')),
    path('users/user_login/', users.views.user_login, name='login')
]

users/urls.py
from django.urls import path
from users import views

app_name = 'users'


urlpatterns = [
    path('login/', views.user_login, name='user_login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render
from items.models import Item
from cart.models import Cart
from users.models import UserProfile
from django.contrib.auth.admin import User
from django.db.models import Q
# Create your views here.


def in_cart_check(item_id, cart_items):
    for cart_item in cart_items:
        if cart_item.id == item_id:
            return True

    return False


def index(request):
    results = Item.objects.all()
    item_status = {}
    current_user_name = request.user.username
    user = User.objects.filter(username=current_user_name).first()
    user_loggedin = UserProfile.objects.filter(user=user).first()
    if user_loggedin is not None:
        cart_items = user_loggedin.cart.cart_item.all()
        for item in results:
            item_status[item.id] = False

        ids = item_status.keys()
        for id in ids:
            if in_cart_check(id, cart_items):
                item_status[id] = True

        final_item_status = []
        for id in ids:
            if item_status[id]:
                final_item_status.append(id)
        return render(request, 'core/index.html', {'results':results, 'final_item_status':final_item_status})

    return render(request, 'core/index.html', {'results':results, 'final_item_status':[]})

templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shopping App</title>
</head>
<body>
<div class="container">
    <ul class="nav">
  <li class="nav-item">
    <a class="navbar-brand active" href="{% url 'core:index' %}">Home</a>
  </li>
    {% if user.is_authenticated %}
      <li class="nav-item">
    <a class="nav-link" href="{% url 'cart:view_cart' %}">Cart</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
  </li>
    {% else %}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'users:user_login' %}">Login</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'users:register' %}">Register</a>
  </li>
    {% endif %}
    <li class="nav-item">
        <form method="GET" action="{% url 'items:search_item' %}">
            <input type="text" placeholder="Search.." name="query"><button type="submit" class="btn btn-primary">Search</button>
        </form>
    </li>
</ul>
</div>
<div class="jumbotron">
{% block content %}

{% endblock %}
</div>
</body>
</html>

templates/core/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="footer navbar-fixed-bottom">
<h1>This is the footer</h1>
</div>
</body>
</html>

templates/core/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}
{% load custom_tags %}
{% block content %}

{% if results %}

{% for result in results %}

  <div class="card shadow p-3 mb-5 bg-white rounded">
    <img height="300px" width="25%" src="{% with result.item_image as image_static %} {% static image_static %} {% endwith %}" alt="Card image cap">
    <div class="card-body">
      <a href="{% url 'items:view_item_details' result.id %}"><h5 class="card-title">{{result.item_name}}</h5></a>
      <p class="card-text">{{result.item_description}}</p>
      <p class="card-text"><small class="text-muted">{{result.item_discount}} % off</small></p>
      {% if result.id in final_item_status %}
      <p class="card-text">Already in cart!</p>
      {% else %}
      <form action="{% url 'cart:add_item' result.id%}">
        <button class="btn btn-primary">Add to cart</button>
      </form>
      {% endif %}
    </div>
    </div>

{% endfor %}
{% else %}
<h1>Your search didn't return anything!</h1>
{% endif %}
{% endblock %}